parameters:
    rizeway_job.logger.class: Rizeway\JobBundle\Logger\DoctrineLogger

services:
    rizeway_job.logger:
        class: %rizeway_job.logger.class%
        arguments: [@doctrine.orm.entity_manager]
